name: Auto Live M3U

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch:      # 支持手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Environment
        run: |
          chmod +x list/update_live.sh
          mkdir -p files down

      - name: Run Update Script
        run: ./list/update_live.sh

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Auto Update live.m3u $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
